services:
  api:
    build:
      context: .
    image: goapplyjob-golang-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./page_extract.db:/app/page_extract.db

  watcher:
    build:
      context: .
    image: goapplyjob-golang-backend
    profiles:
      - workers
    env_file:
      - .env
    command: ["/app/api"]
    volumes:
      - ./page_extract.db:/app/page_extract.db

  importer:
    build:
      context: .
    image: goapplyjob-golang-backend
    profiles:
      - workers
    env_file:
      - .env
    command: ["/app/api"]
    volumes:
      - ./page_extract.db:/app/page_extract.db
