package builtin

import (
	"strings"
	"testing"
)

func TestExtractJobBuildsBuiltInRawJobShape(t *testing.T) {
	htmlText := `
<html>
  <head>
    <link rel="canonical" href="https://builtin.com/job/platform-engineer/12345">
    <script>
      Builtin.jobPostInit({"job":{"howToApply":"https://jobs.acme.example/apply/12345"}});
    </script>
    <script type="application/ld+json">
      {
        "@type": "JobPosting",
        "title": "Platform Engineer",
        "datePosted": "2026-02-12T10:00:00Z",
        "validThrough": "2026-03-12T10:00:00Z",
        "description": "<p>Build internal systems.</p><p>Ship reliable services.</p>",
        "employmentType": "FULL_TIME",
        "jobLocationType": "TELECOMMUTE",
        "jobLocation": [
          {
            "address": {
              "addressLocality": "New York",
              "addressRegion": "NY",
              "addressCountry": "USA"
            }
          },
          {
            "address": {
              "addressLocality": "Austin",
              "addressRegion": "TX",
              "addressCountry": "USA"
            }
          }
        ],
        "identifier": {"value": "12345"},
        "hiringOrganization": {"sameAs": "https://builtin.com/company/acme"},
        "skills": ["Go", "Kubernetes"],
        "keywords": "PostgreSQL, Terraform",
        "baseSalary": {
          "currency": "USD",
          "value": {
            "minValue": 180000,
            "maxValue": 220000,
            "unitText": "year"
          }
        }
      }
    </script>
  </head>
  <body>
    <div>Short BuiltIn summary.</div>
    <div>Summary generated by Built In</div>
    <div>Senior level</div>
  </body>
</html>`
	companyHTML := `
<html>
  <head>
    <link rel="canonical" href="https://builtin.com/company/acme">
    <meta name="description" content="Acme builds infrastructure products.">
    <script>Builtin.companyProfileInit({"companyId":987,"companyName":"Acme","companyAlias":"acme"});</script>
  </head>
  <body>
    <a href="https://acme.example.com">View Website</a>
    <a href="https://linkedin.com/company/acme">LinkedIn</a>
    Year Founded: 2014
    300 Total Employees
  </body>
</html>`

	payload := ExtractJob(htmlText, companyHTML)
	if payload["id"] != 12345 {
		t.Fatalf("expected external job id, got %#v", payload["id"])
	}
	if payload["url"] != "https://jobs.acme.example/apply/12345" {
		t.Fatalf("expected canonical url, got %#v", payload["url"])
	}
	if payload["slug"] != "platform-engineer-12345" {
		t.Fatalf("expected slug from canonical url, got %#v", payload["slug"])
	}
	if payload["employmentType"] != "full-time" {
		t.Fatalf("expected normalized employment type, got %#v", payload["employmentType"])
	}
	if payload["locationType"] != "remote" {
		t.Fatalf("expected normalized location type, got %#v", payload["locationType"])
	}
	if payload["location"] != "New York, NY, USA | Austin, TX, USA" {
		t.Fatalf("expected location label, got %#v", payload["location"])
	}
	if payload["jobDescriptionSummary"] != "Short BuiltIn summary." || payload["twoLineJobDescriptionSummary"] != "Short BuiltIn summary." {
		t.Fatalf("expected BuiltIn summary override, got summary=%#v twoLine=%#v", payload["jobDescriptionSummary"], payload["twoLineJobDescriptionSummary"])
	}
	techStack, _ := payload["techStack"].([]string)
	if len(techStack) != 4 || techStack[0] != "Go" || techStack[3] != "Terraform" {
		t.Fatalf("unexpected tech stack %#v", payload["techStack"])
	}
	company, _ := payload["company"].(map[string]any)
	if company["id"] != float64(987) && company["id"] != 987 {
		t.Fatalf("expected raw company id, got %#v", company["id"])
	}
	if company["slug"] != "acme" {
		t.Fatalf("expected raw company slug, got %#v", company["slug"])
	}
	if payload["isOnLinkedIn"] != false {
		t.Fatalf("expected BuiltIn job to not be marked as LinkedIn, got %#v", payload["isOnLinkedIn"])
	}
	matchKeys, _ := company["companyMatchKey"].([]string)
	if len(matchKeys) != 2 || matchKeys[0] != "domain:example.com" || matchKeys[1] != "subdomain:acme.example.com" {
		t.Fatalf("unexpected company match key %#v", company["companyMatchKey"])
	}
	salaryRange, _ := payload["salaryRange"].(map[string]any)
	if salaryRange["min"] != 180000 || salaryRange["salaryType"] != "per year" {
		t.Fatalf("unexpected salary range %#v", salaryRange)
	}
	if payload["isSenior"] != true || payload["isLead"] != false {
		t.Fatalf("unexpected seniority flags senior=%#v lead=%#v", payload["isSenior"], payload["isLead"])
	}
	states, _ := payload["locationUSStates"].([]string)
	if len(states) != 2 || states[0] != "NY" || states[1] != "TX" {
		t.Fatalf("unexpected state list %#v", payload["locationUSStates"])
	}
}

func TestExtractRoleRequirementsAndCleanDescription(t *testing.T) {
	requirements, cleaned := extractRoleRequirementsAndCleanDescription("What You'll Do\nBuild systems\nRequirements\n5+ years of Python\nStrong SQL skills\nBenefits\nRemote-first")
	if requirements == nil || !strings.Contains(requirements.(string), "5+ years of Python") {
		t.Fatalf("expected requirements extraction, got %#v", requirements)
	}
	if cleaned == nil || strings.Contains(cleaned.(string), "5+ years of Python") {
		t.Fatalf("expected cleaned description without requirements, got %#v", cleaned)
	}
}

func TestExtractIndustrySpecialitiesFromJobPostingHandlesListAndCSV(t *testing.T) {
	values, _ := extractIndustrySpecialitiesFromJobPosting(map[string]any{
		"industry": []any{"Software", "AI, Analytics", "software", "Cloud"},
	}).([]string)
	if len(values) != 4 || values[1] != "AI" || values[2] != "Analytics" {
		t.Fatalf("unexpected industries %#v", values)
	}
}

func TestFallbackCompanyFromJobPosting(t *testing.T) {
	company := fallbackCompanyFromJobPosting(map[string]any{
		"hiringOrganization": map[string]any{
			"name":   "AAA",
			"sameAs": "https://builtin.com/company/aaa",
		},
	}, `<html><body><span>Year Founded: 1902</span><p>We have 14,000 employees in 21 states.</p></body></html>`)
	if company["name"] != "AAA" || company["slug"] != "aaa" {
		t.Fatalf("unexpected fallback company %#v", company)
	}
	if company["founded_year"] != "1902" || company["employee_range"] != "14000" {
		t.Fatalf("unexpected fallback company values %#v", company)
	}
}
