package builtin

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestExtractJobBuildsBuiltInRawJobShape(t *testing.T) {
	htmlText := `
<html>
  <head>
    <link rel="canonical" href="https://builtin.com/job/platform-engineer/12345">
    <script>
      Builtin.jobPostInit({"job":{"howToApply":"https://jobs.acme.example/apply/12345"}});
    </script>
    <script type="application/ld+json">
      {
        "@type": "JobPosting",
        "title": "Platform Engineer",
        "datePosted": "2026-02-12T10:00:00Z",
        "validThrough": "2026-03-12T10:00:00Z",
        "description": "<p>Build internal systems.</p><p>Ship reliable services.</p>",
        "employmentType": "FULL_TIME",
        "jobLocationType": "TELECOMMUTE",
        "jobLocation": [
          {
            "address": {
              "addressLocality": "New York",
              "addressRegion": "NY",
              "addressCountry": "USA"
            }
          },
          {
            "address": {
              "addressLocality": "Austin",
              "addressRegion": "TX",
              "addressCountry": "USA"
            }
          }
        ],
        "identifier": {"value": "12345"},
        "hiringOrganization": {"sameAs": "https://builtin.com/company/acme"},
        "skills": ["Go", "Kubernetes"],
        "keywords": "PostgreSQL, Terraform",
        "baseSalary": {
          "currency": "USD",
          "value": {
            "minValue": 180000,
            "maxValue": 220000,
            "unitText": "year"
          }
        }
      }
    </script>
  </head>
  <body>
    <div>Short BuiltIn summary.</div>
    <div>Summary generated by Built In</div>
    <span>Senior level</span>
  </body>
</html>`
	companyHTML := `
<html>
  <head>
    <link rel="canonical" href="https://builtin.com/company/acme">
    <meta name="description" content="Acme builds infrastructure products.">
    <script>Builtin.companyProfileInit({"companyId":987,"companyName":"Acme","companyAlias":"acme"});</script>
  </head>
  <body>
    <a href="https://acme.example.com">View Website</a>
    <a href="https://linkedin.com/company/acme">LinkedIn</a>
    Year Founded: 2014
    300 Total Employees
  </body>
</html>`

	payload := ExtractJob(htmlText, companyHTML)
	if payload["id"] != "12345" {
		t.Fatalf("expected external job id, got %#v", payload["id"])
	}
	if payload["url"] != "https://jobs.acme.example/apply/12345" {
		t.Fatalf("expected canonical url, got %#v", payload["url"])
	}
	if payload["slug"] != "platform-engineer" {
		t.Fatalf("expected slug from canonical url, got %#v", payload["slug"])
	}
	if payload["employmentType"] != "full_time" {
		t.Fatalf("expected normalized employment type, got %#v", payload["employmentType"])
	}
	if payload["locationType"] != "remote" {
		t.Fatalf("expected normalized location type, got %#v", payload["locationType"])
	}
	if _, ok := payload["location"]; ok {
		t.Fatalf("expected location field to be omitted, got %#v", payload["location"])
	}
	if payload["jobDescriptionSummary"] != "Short BuiltIn summary." || payload["twoLineJobDescriptionSummary"] != "Short BuiltIn summary." {
		t.Fatalf("expected BuiltIn summary override, got summary=%#v twoLine=%#v", payload["jobDescriptionSummary"], payload["twoLineJobDescriptionSummary"])
	}
	techStack, _ := payload["techStack"].([]string)
	if len(techStack) != 0 {
		t.Fatalf("unexpected tech stack %#v", payload["techStack"])
	}
	company, _ := payload["company"].(map[string]any)
	if company["id"] != Source+"_987" {
		t.Fatalf("expected normalized company id string, got %#v", company["id"])
	}
	if company["slug"] != "acme" {
		t.Fatalf("expected raw company slug, got %#v", company["slug"])
	}
	if payload["isOnLinkedIn"] != false {
		t.Fatalf("expected BuiltIn job to not be marked as LinkedIn, got %#v", payload["isOnLinkedIn"])
	}
	salaryRange, _ := payload["salaryRange"].(map[string]any)
	if salaryRange["min"] != 180000 || salaryRange["salaryType"] != "per year" {
		t.Fatalf("unexpected salary range %#v", salaryRange)
	}
	if payload["isSenior"] != true || payload["isLead"] != false {
		t.Fatalf("unexpected seniority flags senior=%#v lead=%#v", payload["isSenior"], payload["isLead"])
	}
	states, _ := payload["locationUSStates"].([]string)
	if len(states) != 2 || states[0] != "New York" || states[1] != "Texas" {
		t.Fatalf("unexpected state list %#v", payload["locationUSStates"])
	}
}

func TestExtractJobSkipsNullLikeUSState(t *testing.T) {
	htmlText := `
<html>
  <head>
    <link rel="canonical" href="https://builtin.com/job/platform-engineer/12345">
    <script type="application/ld+json">
      {
        "@type": "JobPosting",
        "title": "Platform Engineer",
        "datePosted": "2026-02-12T10:00:00Z",
        "description": "<p>Build internal systems.</p>",
        "jobLocationType": "TELECOMMUTE",
        "jobLocation": [
          {
            "address": {
              "addressLocality": "Austin",
              "addressRegion": "null",
              "addressCountry": "USA"
            }
          },
          {
            "address": {
              "addressLocality": "New York",
              "addressRegion": "NY",
              "addressCountry": "USA"
            }
          }
        ],
        "identifier": {"value": "12345"},
        "hiringOrganization": {"sameAs": "https://builtin.com/company/acme"}
      }
    </script>
  </head>
  <body></body>
</html>`
	payload := ExtractJob(htmlText, "")
	states, _ := payload["locationUSStates"].([]string)
	if len(states) != 1 || states[0] != "New York" {
		t.Fatalf("unexpected state list %#v", payload["locationUSStates"])
	}
}

func TestExtractSeniorityLabelPrefersSpanBadge(t *testing.T) {
	htmlText := `
<html>
  <body>
    <span class="badge">Senior level</span>
    <div>Senior level</div>
  </body>
</html>`
	label := extractSeniorityLabel(htmlText)
	if strings.ToLower(strings.TrimSpace(label)) != "senior level" {
		t.Fatalf("expected senior level label, got %#v", label)
	}
}

func TestExtractRoleRequirementsAndCleanDescription(t *testing.T) {
	requirements, cleaned := extractRoleRequirementsAndCleanDescription("What You'll Do\nBuild systems\nRequirements\n5+ years of Python\nStrong SQL skills\nBenefits\nRemote-first")
	if requirements == nil || !strings.Contains(requirements.(string), "5+ years of Python") {
		t.Fatalf("expected requirements extraction, got %#v", requirements)
	}
	if cleaned == nil || strings.Contains(cleaned.(string), "5+ years of Python") {
		t.Fatalf("expected cleaned description without requirements, got %#v", cleaned)
	}
}

func TestExtractRoleRequirementsFromBoldSectionHeaders(t *testing.T) {
	descriptionHTML := `
    <div>
      <p><b>Overview</b><br>Build scalable backend services.</p>
      <p><b>Duties</b></p>
      <ul>
        <li>Design APIs</li>
        <li>Own incident response</li>
      </ul>
      <p><b>Requirements</b></p>
      <ul>
        <li>5+ years Python</li>
        <li>Strong SQL</li>
      </ul>
      <p><b>Benefits</b></p>
      <ul><li>Health insurance</li></ul>
    </div>`
	requirements, cleanedDescription := extractRoleRequirementsAndCleanDescription(descriptionHTML)
	if requirements == nil || !strings.Contains(requirements.(string), "5+ years Python") {
		t.Fatalf("expected requirements from bold section, got %#v", requirements)
	}
	if strings.Contains(requirements.(string), "Health insurance") {
		t.Fatalf("did not expect benefits in requirements %#v", requirements)
	}
	if cleanedDescription == nil || !strings.Contains(cleanedDescription.(string), "Build scalable backend services.") {
		t.Fatalf("expected cleaned description to include overview %#v", cleanedDescription)
	}
}

func TestExtractJobUsesTooltipCountriesForMultipleBuiltinLocations(t *testing.T) {
	htmlPath := filepath.Join("..", "..", "..", "test-extract", "builtin", "raw-job-2.html")
	htmlBytes, err := os.ReadFile(htmlPath)
	if err != nil {
		t.Fatalf("read html: %v", err)
	}

	payload := ExtractJobFromHTML(string(htmlBytes), "")
	locationCountries, _ := payload["locationCountries"].([]string)
	expectedCountries := []string{"Argentina", "United States"}
	if !reflect.DeepEqual(locationCountries, expectedCountries) {
		t.Fatalf("unexpected locationCountries got=%#v want=%#v", locationCountries, expectedCountries)
	}
	if payload["locationCity"] != "Mexico" {
		t.Fatalf("expected locationCity from jobLocation only, got %#v", payload["locationCity"])
	}
	locationStates, _ := payload["locationUSStates"].([]string)
	expectedStates := []string{"Indiana"}
	if !reflect.DeepEqual(locationStates, expectedStates) {
		t.Fatalf("expected locationUSStates from jobLocation only got=%#v want=%#v", locationStates, expectedStates)
	}
}

func TestExtractIndustrySpecialitiesFromJobPostingHandlesListAndCSV(t *testing.T) {
	values, _ := extractIndustrySpecialitiesFromJobPosting(map[string]any{
		"industry": []any{"Software", "AI, Analytics", "software", "Cloud"},
	}).([]string)
	if len(values) != 4 || values[1] != "AI" || values[2] != "Analytics" {
		t.Fatalf("unexpected industries %#v", values)
	}
}

func TestFallbackCompanyFromJobPosting(t *testing.T) {
	company := fallbackCompanyFromJobPosting(map[string]any{
		"hiringOrganization": map[string]any{
			"name":   "AAA",
			"sameAs": "https://builtin.com/company/aaa",
		},
	}, `<html><body><h2>What We Do</h2><p>Paragraph A</p><p>Paragraph B</p><h2>Other</h2><p>Ignore this.</p><span>Year Founded: 1902</span><p>We have 14,000 employees in 21 states.</p></body></html>`)
	if company["name"] != "AAA" || company["slug"] != "aaa" {
		t.Fatalf("unexpected fallback company %#v", company)
	}
	if company["founded_year"] != "1902" || company["employee_range"] != "14000" {
		t.Fatalf("unexpected fallback company values %#v", company)
	}
	if company["external_company_id"] != Source+"_company_aaa" {
		t.Fatalf("unexpected fallback company external id %#v", company["external_company_id"])
	}
	if company["tagline"] != "Paragraph A\nParagraph B" {
		t.Fatalf("unexpected fallback company tagline %#v", company["tagline"])
	}
}

func TestExtractJobFromHTMLUsesFallbackCompanyWhenCompanyMissing(t *testing.T) {
	htmlText := `
<html>
  <head>
    <script type="application/ld+json">
      {
        "@type": "JobPosting",
        "title": "Platform Engineer",
        "description": "<p>Build systems.</p>",
        "employmentType": "FULL_TIME",
        "jobLocationType": "TELECOMMUTE",
        "hiringOrganization": {"sameAs": "https://builtin.com/company/acme"}
      }
    </script>
  </head>
  <body></body>
</html>`
	payload := ExtractJobFromHTML(htmlText, "https://builtin.com/job/platform-engineer/12345")
	company, _ := payload["company"].(map[string]any)
	if company["slug"] != "acme" {
		t.Fatalf("expected fallback company slug, got %#v", company["slug"])
	}
	if company["id"] != Source+"_company_acme" {
		t.Fatalf("expected fallback company id, got %#v", company["id"])
	}
}

func TestExtractJobFromHTMLMapsJobBenefitsFromLDJSON(t *testing.T) {
	htmlText := `
<html>
  <head>
    <link rel="canonical" href="https://builtin.com/job/test-benefits/10" />
    <script type="application/ld+json">
      {
        "@context":"http://schema.org/",
        "@type":"JobPosting",
        "title":"Platform Engineer",
        "employmentType":"FULL_TIME",
        "hiringOrganization":{"@type":"Organization","name":"Acme","sameAs":"https://builtin.com/company/acme"},
        "jobLocation":[{"@type":"Place","address":{"@type":"PostalAddress","addressCountry":"US"}}],
        "applicantLocationRequirements":[{"@type":"Country","name":"United States"}],
        "description":"<b>Job Description</b><br>Build internal platform.<br><b>Requirements</b><br>5+ years backend.",
        "jobBenefits":"<p>Medical, dental, vision</p><p>401(k) match</p>"
      }
    </script>
  </head>
  <body></body>
</html>`
	payload := ExtractJobFromHTML(htmlText, "https://builtin.com/job/test-benefits/10")
	if payload["benefits"] != "<p>Medical, dental, vision</p><p>401(k) match</p>" {
		t.Fatalf("expected benefits passthrough, got %#v", payload["benefits"])
	}
	if payload["roleRequirements"] != nil {
		t.Fatalf("expected nil role requirements when preserving html description, got %#v", payload["roleRequirements"])
	}
	description, _ := payload["roleDescription"].(string)
	if !strings.Contains(description, "<b>Job Description</b>") {
		t.Fatalf("expected raw html roleDescription, got %#v", payload["roleDescription"])
	}
}

func TestInferLevelFlagsDetectsSrWithPunctuation(t *testing.T) {
	flags := inferLevelFlags("Sr., Software Engineer", "")
	if flags["isSenior"] != true {
		t.Fatalf("expected isSenior=true, got %#v", flags)
	}
	if flags["isMidLevel"] != false {
		t.Fatalf("expected isMidLevel=false, got %#v", flags)
	}
}

func TestExtractCompanyInfoDoesNotUseInitOrMetaForTagline(t *testing.T) {
	companyHTML := `
<html>
  <head>
    <meta name="description" content="Meta description fallback">
    <script>Builtin.companyProfileInit({"companyId":12,"companyAlias":"acme","companyName":"Acme","description":"Init description fallback"});</script>
  </head>
  <body></body>
</html>`
	company := extractCompanyInfo(companyHTML, "https://builtin.com/company/acme")
	if company["tagline"] != nil {
		t.Fatalf("expected nil tagline without mission block, got %#v", company["tagline"])
	}
}

func TestExtractCompanyInfoUsesMissionBlockTagline(t *testing.T) {
	companyHTML := `
<html>
  <body>
    <div x-ref="companyMission">
      <p>We help modern teams automate recruiting.</p>
      <p>Built for distributed companies.</p>
    </div>
  </body>
</html>`
	company := extractCompanyInfo(companyHTML, "https://builtin.com/company/acme")
	if company["tagline"] != "We help modern teams automate recruiting.\nBuilt for distributed companies." {
		t.Fatalf("unexpected mission tagline %#v", company["tagline"])
	}
}

func TestExtractCompanyInfoMissionBlockHandlesBRAndNestedText(t *testing.T) {
	companyHTML := `
<html>
  <body>
    <div x-ref="companyMission">
      We build tools<br>for hiring teams.
      <span>Fast and reliable.</span>
    </div>
  </body>
</html>`
	company := extractCompanyInfo(companyHTML, "https://builtin.com/company/acme")
	if company["tagline"] != "We build tools\nfor hiring teams.\nFast and reliable." {
		t.Fatalf("unexpected mission block tagline %#v", company["tagline"])
	}
}
